[app]
debug = true
language = 'pl'

air-service = 'dummy'
time-service = 'chrono'
weather-service = 'dummy'

[display]
width = 800
height = 480

[services.airly]
api-key = ''

[services.dark-sky]
api-key = '87094ed2a7d2414ed1cb9b2cd055e12a'
latitude = 51.1544397
longitude = 17.0431444

[services.open-weather-map]
api-key = '955b19bb75383e80889ec01284a0a237'
city = 'Wrocław'
country = 'Poland'