[package]
name = "lib_backend_dummy_provider"
version = "0.1.0"
license = "MIT"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
lib_backend_common = { path = "../../backend-common" }
log = "0.4"